name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    commits:
        name: Commits
        uses: NixySoftware/.github/.github/workflows/commits.yml@d111cf0f030e8e9838dbc63fa137c18af021610c

    rust:
        name: Rust
        uses: NixySoftware/.github/.github/workflows/rust.yml@d111cf0f030e8e9838dbc63fa137c18af021610c

    typescript:
        name: TypeScript
        uses: NixySoftware/.github/.github/workflows/typescript.yml@d111cf0f030e8e9838dbc63fa137c18af021610c
        with:
            enable-lint: false
