name: Publish

on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish
        uses: NixySoftware/.github/.github/workflows/publish.yml@d111cf0f030e8e9838dbc63fa137c18af021610c
