name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: NixySoftware/.github/.github/workflows/release.yml@d111cf0f030e8e9838dbc63fa137c18af021610c
        with:
            bump: ${{ inputs.bump }}
